project:
  type: website
  output-dir: docs

website:
  title: "portfolio"
  site-url: "https://maridch.github.io/Portfolio"
  repo-url: "https://github.com/maridch/Portfolio"
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



